"""Константы, используемые в UI"""

SIZE_WIDTH_BUTTON = 500
SIZE_HEIGHT_BUTTON = 75
SIZE_WIDTH_LINE_EDIT = 350
SIZE_WIDTH_TOP_BUTTON = 100
SIZE_WIDTH_TYPICAL_BUTTON = 270
SIZE_HEIGHT_TOP_BUTTON = 50
INF = 10**4
SIZE_WIDTH_WINDOW = 1200
SIZE_HEIGHT_WINDOW = 720
SIZE_WIDTH_HOME_BUTTON = 100
SIZE_HEIGHT_HOME_BUTTON = 30
INDENT_HOME_BUTTON = 10
SIZE_TEXT = 26

HOME = "Домой"
CREATE_BANK = "Создать банк"
NAME_BANK = "Имя банка:"
FIRST_NAME = "Имя:"
SECOND_NAME = "Фамилия:"
SERIA_PASSPORT = "Серия паспорта:"
NUMBER_PASSPORT = "Номер паспорта:"
ADDRESS = "Адресс:"
SIGN_UP = "Зарегистрироваться"
SIGN_IN = "Войти"
DELETE_BANK_ACCOUNT = "Удалить счёт"
TOP_UP = "Пополнить"
WITHDRAW = "Снять"
TRANSFER = "Перевести"
CREATE_BANK_ACCOUNT = "Открыть счёт"
CHANGE_NAME_BANK = "Сменить имя"
SET_LIMIT = "Установить кредитный лимит"
LIMIT = "Кредитный лимит:"
MY_TRANSACTIONS = "Мои транзакции"
WARNING = "Предупреждение"
NOT_ENOUGH_DATA = "Имя, фамилия и адресс обязательны"
CLIENT_EXIST = "Вы уже зарегистрированы"
CLIENT_IS_NOT_EXIST = "Пользователь не найден"
DEBIT = "Дебетовый"
CREDIT = "Кредитный"
DEPOSIT = "Депозит"
TYPE_BANK_ACCOUNTS = "Тип счёта:"
BALANCE = "Баланс:"
BANK = "Банк:"
CANCEL = "Отмена"
CREATE = "Создать"
INVALID_AMOUNT_MONEY = "Некорректное значение"
LOW_BALANCE = "Недостаточно средств"
DEPOSIT_NOT_FINISHED = "Срок депозита не истёк"
NOT_PASSPORT = "Ваш аккаунт имеет ограничения\nВведите паспортные данные"
SURE_DEL_ACCOUNT = "Вы уверены, что хотите удалить счёт?"
ESCAPE = "Назад"
TYPE_TRANSACTION = "Тип транзакции:"
WHOM = "Кому:"
AMOUNT = "Сумма:"
TYPE_TOP_UP = "пополнение"
TYPE_WITHDRAW = "снятие"
TYPE_TRANSFER = "перевод"
CANCEL_TRANSACTION = "Отменить"
BACK_TRANSACTION = "Вернуть"
CANNOT_EXEC_OPERATION = "Невозможно выполнить операцию"
NAME_ACCOUNT = "Название счёта:"
TRANSFER_FIRST_NAME = "Кому (имя):"
TRANSFER_SECOND_NAME = "Кому (фамилия):"
CHANGE_DATA = "Изменить персональные данные"
SAVE = "Сохранить"
INVALID_PASSPORT = "Некорректные данные паспорта"
DEFAULT_LIMIT = "10000.00"
BANK_NOT_FOUND = "Банк не найден"
DONE = "Готово!"
NAME_EXIST = "Имя занято"
BANK_CLIENT = "Клиент банка"
EMPTY = ""
OK = "&OK"
TIMES = "Times"
